version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  jobs:
    build: .
    environment:
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - TWITTER_CONSUMER_KEY=${TWITTER_ACCESS_TOKEN_SECRET}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
