version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  jobs:
    build: .
    environment:
      - LYRICS_MIXER_TWITTER_ACCESS_TOKEN=${LYRICS_MIXER_TWITTER_ACCESS_TOKEN}
      - LYRICS_MIXER_TWITTER_ACCESS_TOKEN_SECRET=${LYRICS_MIXER_TWITTER_ACCESS_TOKEN_SECRET}
      - LYRICS_MIXER_TWITTER_CONSUMER_KEY=${LYRICS_MIXER_TWITTER_CONSUMER_KEY}
      - LYRICS_MIXER_TWITTER_CONSUMER_SECRET=${LYRICS_MIXER_TWITTER_CONSUMER_SECRET}
      - LYRICS_MIXER_DATABASE_URL=${LYRICS_MIXER_DATABASE_URL}
    depends_on:
      - db
